name: Build Templates
on: push
  # release:
  #   types: [created]

jobs:
  windows:
    name: Create windows templates
    runs-on: windows-2019
    steps:
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Setup GO
      uses: actions/setup-go@v1
      with:
        go-version: '1.10.x'

    - name: Install wget
      run: pip3 install wget

    - name: Checkout
      uses: actions/checkout@v1

    - name: Download Resource Hacker
      run: |
        python -m wget --output %GITHUB_WORKSPACE%\resource_hacker.zip http://angusj.com/resourcehacker/resource_hacker.zip
        7z x %GITHUB_WORKSPACE%\resource_hacker.zip -o%GITHUB_WORKS%\resource_hacker

    - name: Compile VersionInfo
      run: |
        cd %GITHUB_WORKSPACE%\.
        .\resource_hacker\ResourceHacker.exe -open .\windows\VersionInfo1.rc -save .\windows\VersionInfo1.res -action compile

    - name: Debug Info
      run: |
        cd %GITHUB_WORKSPACE%\..
        echo DIRECTORY
        dir
        echo TREE
        tree
        echo PATH
        echo %path%

    # - name: Download LÖVE
    #   run:
    # - name: Change the executable icon
    #   run:
    # - name: Package the build template
    #   run:
    # - name: Upload the build template
    #   run: