name: Build Templates
on: push
  # release:
  #   types: [created]

jobs:
  windows:
    name: Create windows templates
    runs-on: windows-2019
    steps:
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'

    # - name: Setup GO
    #   uses: actions/setup-go@v1
    #   with:
    #     go-version: '1.10.x'

    - name: Install wget
      run: pip3 install wget

    - name: Checkout
      uses: actions/checkout@v1

    - name: Download Resource Hacker
      run: |
        python -m wget --output %GITHUB_WORKSPACE%\resource_hacker.zip http://angusj.com/resourcehacker/resource_hacker.zip
        7z x %GITHUB_WORKSPACE%\resource_hacker.zip -o%GITHUB_WORKSPACE%\resource_hacker

    - name: Compile VersionInfo
      run: |
        cd %GITHUB_WORKSPACE%
        .\resource_hacker\ResourceHacker.exe -open .\windows\VersionInfo1.rc -save .\windows\VersionInfo1.res -action compile -log CONSOLE
    
    - name: Download LÖVE
      run: |
        python -m wget --output %GITHUB_WORKSPACE%\love_win32.zip https://bitbucket.org/rude/love/downloads/love-11.2-win32.zip
        7z x %GITHUB_WORKSPACE%\love_win32.zip -o%GITHUB_WORKSPACE%\love_win32
    
    - name: Patch LÖVE
      run: |
        cd %GITHUB_WORKSPACE%
        echo Replacing icon files
        copy .\windows\icon.ico .\love\love.ico
        copy .\windows\icon.ico .\love\game.ico
        echo Patching love.exe icon
        resource_hacker\ResourceHacker.exe -open .\love_win32\love.exe -save .\love_win32\love.exe -action addoverwrite -res .\love_win32\love.ico -mask ICONGROUP,1,1033 -log CONSOLE
        echo Patching lovec.exe icon
        resource_hacker\ResourceHacker.exe -open .\love_win32\lovec.exe -save .\love_win32\lovec.exe -action addoverwrite -res .\love_win32\love.ico -mask ICONGROUP,1,1033 -log CONSOLE
        echo Patching love.exe VersionInfo
        resource_hacker\ResourceHacker.exe -open .\love_win32\love.exe -save .\love_win32\love.exe -action addoverwrite -res .\windows\VersionInfo1.res -mask VERSIONINFO,1,1033 -log CONSOLE
        echo Patching lovec.exe VersionInfo
        resource_hacker\ResourceHacker.exe -open .\love_win32\lovec.exe -save .\love_win32\lovec.exe -action addoverwrite -res .\windows\VersionInfo1.res -mask VERSIONINFO,1,1033 -log CONSOLE
    
    - name: Uploading Debug Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: love_win32
        path: love_win32

    - name: Debug Info
      run: |
        cd %GITHUB_WORKSPACE%\love_win32\
        dir

    # - name: Download LÖVE
    #   run:
    # - name: Change the executable icon
    #   run:
    # - name: Package the build template
    #   run:
    # - name: Upload the build template
    #   run: