name: Build Templates
on: push
  # release:
  #   types: [created]

jobs:
  windows:
    name: Create windows templates
    runs-on: windows-2019
    steps:
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Install wget
      run: pip3 install wget

    - name: Checkout
      uses: actions/checkout@v1

    - name: Download Resource Hacker
      run: |
        python -m wget --output %GITHUB_WORKSPACE%\resource_hacker.zip http://angusj.com/resourcehacker/resource_hacker.zip
        7z x %GITHUB_WORKSPACE%\resource_hacker.zip -o%GITHUB_WORKSPACE%\resource_hacker

    - name: Compile VersionInfo
      run: |
        cd %GITHUB_WORKSPACE%
        .\resource_hacker\ResourceHacker.exe -open .\windows\VersionInfo_love.rc -save .\windows\VersionInfo_love.res -action compile -log CONSOLE
        .\resource_hacker\ResourceHacker.exe -open .\windows\VersionInfo_lovec.rc -save .\windows\VersionInfo_lovec.res -action compile -log CONSOLE
    
    - name: Download LÖVE 32-bit
      run: |
        python -m wget --output %GITHUB_WORKSPACE%\love_win32.zip https://bitbucket.org/rude/love/downloads/love-11.2-win32.zip
        7z x %GITHUB_WORKSPACE%\love_win32.zip -o%GITHUB_WORKSPACE%\love_win32
        move /Y %GITHUB_WORKSPACE%\love_win32\love-11.2.0-win32\*.* %GITHUB_WORKSPACE%\love_win32\
        del /Q %GITHUB_WORKSPACE%\love_win32\love-11.2.0-win32
    
    - name: Patch LÖVE 32-bit
      run: |
        cd %GITHUB_WORKSPACE%\
        echo Copying bin files
        copy .\windows\bin\i686\*.* .\love_win32\
        mkdir .\love_win32\lua\
        copy .\windows\bin\i686\lua\*.* .\love_win32\
        echo Replacing icon files
        copy .\windows\icon.ico .\love_win32\love.ico
        copy .\windows\icon.ico .\love_win32\game.ico
        echo Patching love.exe icon
        .\resource_hacker\ResourceHacker.exe -open .\love_win32\love.exe -save .\love_win32\love.exe -action addoverwrite -res .\love_win32\love.ico -mask ICONGROUP,1,1033 -log CONSOLE
        echo Patching lovec.exe icon
        .\resource_hacker\ResourceHacker.exe -open .\love_win32\lovec.exe -save .\love_win32\lovec.exe -action addoverwrite -res .\love_win32\love.ico -mask ICONGROUP,1,1033 -log CONSOLE
        echo Patching love.exe VersionInfo
        .\resource_hacker\ResourceHacker.exe -open .\love_win32\love.exe -save .\love_win32\love.exe -action addoverwrite -res .\windows\VersionInfo_love.res -mask VERSIONINFO,1,1033 -log CONSOLE
        echo Patching lovec.exe VersionInfo
        .\resource_hacker\ResourceHacker.exe -open .\love_win32\lovec.exe -save .\love_win32\lovec.exe -action addoverwrite -res .\windows\VersionInfo_lovec.res -mask VERSIONINFO,1,1033 -log CONSOLE
    
    - name: Upload love_win32 artifact
      uses: actions/upload-artifact@v1
      with:
        name: love_win32
        path: love_win32

    - name: Download LÖVE 64-bit
      run: |
        python -m wget --output %GITHUB_WORKSPACE%\love_win64.zip https://bitbucket.org/rude/love/downloads/love-11.2-win64.zip
        7z x %GITHUB_WORKSPACE%\love_win64.zip -o%GITHUB_WORKSPACE%\love_win64
        move /Y %GITHUB_WORKSPACE%\love_win64\love-11.2.0-win64\*.* %GITHUB_WORKSPACE%\love_win64\
        del /Q %GITHUB_WORKSPACE%\love_win64\love-11.2.0-win64

    - name: Patch LÖVE 64-bit
      run: |
        cd %GITHUB_WORKSPACE%\
        echo Copying bin files
        copy .\windows\bin\x86_64\*.* .\love_win64\
        mkdir .\love_win64\lua\
        copy .\windows\bin\i686\lua\*.* .\love_win64\
        echo Replacing icon files
        copy .\windows\icon.ico .\love_win64\love.ico
        copy .\windows\icon.ico .\love_win64\game.ico
        echo Patching love.exe icon
        .\resource_hacker\ResourceHacker.exe -open .\love_win64\love.exe -save .\love_win64\love.exe -action addoverwrite -res .\love_win64\love.ico -mask ICONGROUP,1,1033 -log CONSOLE
        echo Patching lovec.exe icon
        .\resource_hacker\ResourceHacker.exe -open .\love_win64\lovec.exe -save .\love_win64\lovec.exe -action addoverwrite -res .\love_win64\love.ico -mask ICONGROUP,1,1033 -log CONSOLE
        echo Patching love.exe VersionInfo
        .\resource_hacker\ResourceHacker.exe -open .\love_win64\love.exe -save .\love_win64\love.exe -action addoverwrite -res .\windows\VersionInfo_love.res -mask VERSIONINFO,1,1033 -log CONSOLE
        echo Patching lovec.exe VersionInfo
        .\resource_hacker\ResourceHacker.exe -open .\love_win64\lovec.exe -save .\love_win64\lovec.exe -action addoverwrite -res .\windows\VersionInfo_lovec.res -mask VERSIONINFO,1,1033 -log CONSOLE
    
    - name: Upload love_win64 artifact
      uses: actions/upload-artifact@v1
      with:
        name: love_win64
        path: love_win64
  
  macos:
    name: Create macos templates
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Download LÖVE macOS
      run: |
        cd $GITHUB_WORKSPACE
        echo Downloading LÖVE
        wget -v -O love_macos.zip https://bitbucket.org/rude/love/downloads/love-11.2-macos.zip
        echo Extracting
        unzip love_macos.zip -d love_macos
    
    - name: Patch Info.plist
      run: luajit $GITHUB_WORKSPACE/macos/patch_info_plist.lua
    
    - name: Upload love_macos artifact
      uses: actions/upload-artifact@v1
      with:
        name: love_macos
        path: love_macos
  
  release:
    name: Upload into github releases
    needs: [windows, macos]
    runs-on: ubuntu-18.04
    steps:
    - name: Setup GO
      uses: actions/setup-go@v1
      with:
        go-version: '1.10.x'
    
    - name: Install github-release
      run: go get github.com/gableroux/github-release
    
    - name: Download love_win32 artifact
      uses: actions/download-artifact@v1
      with:
        name: love_win32
        path: love_win32
    - name: Download love_win64 artifact
      uses: actions/download-artifact@v1
      with:
        name: love_win64
        path: love_win64
    - name: Download love_macos artifact
      uses: actions/download-artifact@v1
      with:
        name: love_macos
        path: love_macos