name: Build Templates
on: push
  # release:
  #   types: [created]

jobs:
  windows:
    name: Create windows templates
    runs-on: windows-2019
    steps:
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Install wget
      run: pip3 install wget

    - name: Checkout
      uses: actions/checkout@v1

    - name: Download Resource Hacker
      run: |
        python -m wget --output %GITHUB_WORKSPACE%\resource_hacker.zip http://angusj.com/resourcehacker/resource_hacker.zip
        7z x %GITHUB_WORKSPACE%\resource_hacker.zip -o%GITHUB_WORKSPACE%\resource_hacker

    - name: Compile VersionInfo
      run: |
        cd %GITHUB_WORKSPACE%
        .\resource_hacker\ResourceHacker.exe -open .\windows\VersionInfo_love.rc -save .\windows\VersionInfo_love.res -action compile -log CONSOLE
        .\resource_hacker\ResourceHacker.exe -open .\windows\VersionInfo_lovec.rc -save .\windows\VersionInfo_lovec.res -action compile -log CONSOLE
    
    - name: Download LÖVE 32-bit
      run: |
        set /p LOVE_VERSION=<%GITHUB_WORKSPACE%\LOVE_VERSION.txt
        python -m wget --output %GITHUB_WORKSPACE%\love_win32.zip https://bitbucket.org/rude/love/downloads/love-%LOVE_VERSION%-win32.zip
        7z x %GITHUB_WORKSPACE%\love_win32.zip -o%GITHUB_WORKSPACE%\love_win32
        move /Y %GITHUB_WORKSPACE%\love_win32\love-%LOVE_VERSION%.0-win32\*.* %GITHUB_WORKSPACE%\love_win32\
        del /Q %GITHUB_WORKSPACE%\love_win32\love-%LOVE_VERSION%.0-win32
    
    - name: Patch LÖVE 32-bit
      run: |
        cd %GITHUB_WORKSPACE%\
        echo Copying bin files
        copy .\windows\bin\i686\*.* .\love_win32\
        mkdir .\love_win32\lua\
        copy .\windows\bin\i686\lua\*.* .\love_win32\
        echo Replacing icon files
        copy .\windows\icon.ico .\love_win32\love.ico
        copy .\windows\icon.ico .\love_win32\game.ico
        echo Adding license files
        copy .\LIKO-12-license.txt .\love_win32\LIKO-12-license.txt
        move .\love_win32\license.txt .\love_win32\LOVE-license.txt
        echo Patching love.exe icon
        .\resource_hacker\ResourceHacker.exe -open .\love_win32\love.exe -save .\love_win32\love.exe -action addoverwrite -res .\love_win32\love.ico -mask ICONGROUP,1,1033 -log CONSOLE
        echo Patching lovec.exe icon
        .\resource_hacker\ResourceHacker.exe -open .\love_win32\lovec.exe -save .\love_win32\lovec.exe -action addoverwrite -res .\love_win32\love.ico -mask ICONGROUP,1,1033 -log CONSOLE
        echo Patching love.exe VersionInfo
        .\resource_hacker\ResourceHacker.exe -open .\love_win32\love.exe -save .\love_win32\love.exe -action addoverwrite -res .\windows\VersionInfo_love.res -mask VERSIONINFO,1,1033 -log CONSOLE
        echo Patching lovec.exe VersionInfo
        .\resource_hacker\ResourceHacker.exe -open .\love_win32\lovec.exe -save .\love_win32\lovec.exe -action addoverwrite -res .\windows\VersionInfo_lovec.res -mask VERSIONINFO,1,1033 -log CONSOLE
    
    - name: Upload love_win32 artifact
      uses: actions/upload-artifact@v1
      with:
        name: love_win32
        path: love_win32

    - name: Download LÖVE 64-bit
      run: |
        set /p LOVE_VERSION=<%GITHUB_WORKSPACE%\LOVE_VERSION.txt
        python -m wget --output %GITHUB_WORKSPACE%\love_win64.zip https://bitbucket.org/rude/love/downloads/love-%LOVE_VERSION%-win64.zip
        7z x %GITHUB_WORKSPACE%\love_win64.zip -o%GITHUB_WORKSPACE%\love_win64
        move /Y %GITHUB_WORKSPACE%\love_win64\love-%LOVE_VERSION%.0-win64\*.* %GITHUB_WORKSPACE%\love_win64\
        del /Q %GITHUB_WORKSPACE%\love_win64\love-%LOVE_VERSION%.0-win64

    - name: Patch LÖVE 64-bit
      run: |
        cd %GITHUB_WORKSPACE%\
        echo Copying bin files
        copy .\windows\bin\x86_64\*.* .\love_win64\
        mkdir .\love_win64\lua\
        copy .\windows\bin\i686\lua\*.* .\love_win64\
        echo Replacing icon files
        copy .\windows\icon.ico .\love_win64\love.ico
        copy .\windows\icon.ico .\love_win64\game.ico
        echo Adding license files
        copy .\LIKO-12-license.txt .\love_win64\LIKO-12-license.txt
        move .\love_win64\license.txt .\love_win64\LOVE-license.txt
        echo Patching love.exe icon
        .\resource_hacker\ResourceHacker.exe -open .\love_win64\love.exe -save .\love_win64\love.exe -action addoverwrite -res .\love_win64\love.ico -mask ICONGROUP,1,1033 -log CONSOLE
        echo Patching lovec.exe icon
        .\resource_hacker\ResourceHacker.exe -open .\love_win64\lovec.exe -save .\love_win64\lovec.exe -action addoverwrite -res .\love_win64\love.ico -mask ICONGROUP,1,1033 -log CONSOLE
        echo Patching love.exe VersionInfo
        .\resource_hacker\ResourceHacker.exe -open .\love_win64\love.exe -save .\love_win64\love.exe -action addoverwrite -res .\windows\VersionInfo_love.res -mask VERSIONINFO,1,1033 -log CONSOLE
        echo Patching lovec.exe VersionInfo
        .\resource_hacker\ResourceHacker.exe -open .\love_win64\lovec.exe -save .\love_win64\lovec.exe -action addoverwrite -res .\windows\VersionInfo_lovec.res -mask VERSIONINFO,1,1033 -log CONSOLE
    
    - name: Upload love_win64 artifact
      uses: actions/upload-artifact@v1
      with:
        name: love_win64
        path: love_win64
  
  linux:
    name: Create linux templates
    runs-on: ubuntu-18.04
    steps:
    - name: Update APT packages
      run: sudo apt-get update
    
    - name: Install LuaJIT
      run: sudo apt-get install luajit

    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Download AppImages
      run: luajit $GITHUB_WORKSPACE/linux/download_appimages.lua
    
    - name: Patch AppImages
      run: luajit $GITHUB_WORKSPACE/linux/patch_appimages.lua

    - name: Upload LIKO-12-x86_64.AppImage artifact
      uses: actions/upload-artifact@v1
      with:
        name: love_linux
        path: LIKO-12-x86_64.AppImage
  
  macos:
    name: Create macos template
    runs-on: ubuntu-18.04
    steps:
    - name: Update APT packages
      run: sudo apt-get update
    
    - name: Install LuaJIT
      run: sudo apt-get install luajit

    - name: Checkout
      uses: actions/checkout@v1

    - name: Download LÖVE macOS
      run: |
        cd $GITHUB_WORKSPACE
        LOVE_VERSION=`cat LOVE_VERSION.txt`
        echo Downloading LÖVE
        wget -v -O love_macos_original.zip https://bitbucket.org/rude/love/downloads/love-$LOVE_VERSION-macos.zip
        echo Extracting
        unzip love_macos_original.zip -d love_macos
    
    - name: Patch Info.plist
      run: luajit $GITHUB_WORKSPACE/macos/patch_info_plist.lua

    - name: Replacing some resources
      run: |
        cd $GITHUB_WORKSPACE
        cp -f -v macos/icon.icns "love_macos/love.app/Contents/Resources/OS X AppIcon.icns"
        cp -f -v macos/icon.icns love_macos/love.app/Contents/Resources/GameIcon.icns
        cp -f -v LIKO-12-license.txt love_macos/love.app/Contents/Resources/LIKO-12-license.txt
        mv -f -v love_macos/love.app/Contents/Resources/license.txt love_macos/love.app/Contents/Resources/LOVE-license.txt

    - name: Rename love.app into LIKO-12.app
      run: mv -f -v $GITHUB_WORKSPACE/love_macos/love.app $GITHUB_WORKSPACE/love_macos/LIKO-12.app
    
    - name: Pack macOS template
      run: zip -y -r $GITHUB_WORKSPACE/love_macos.zip $GITHUB_WORKSPACE/love_macos/
    
    - name: Upload love_macos artifact
      uses: actions/upload-artifact@v1
      with:
        name: love_macos
        path: love_macos.zip
  
  release:
    name: Upload into github releases
    needs: [windows, linux, macos]
    runs-on: ubuntu-18.04
    steps:
    - name: Update APT packages
      run: sudo apt-get update
    
    - name: Install LuaJIT
      run: sudo apt-get install luajit
      
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Download love_win32 artifact
      uses: actions/download-artifact@v1
      with:
        name: love_win32
        path: love_win32
    - name: Download love_win64 artifact
      uses: actions/download-artifact@v1
      with:
        name: love_win64
        path: love_win64
    - name: Download love_linux artifact
      uses: actions/download-artifact@v1
      with:
        name: love_linux
        path: LIKO-12-x86_64.AppImage
    - name: Download love_macos artifact
      uses: actions/download-artifact@v1
      with:
        name: love_macos
        path: love_macos
    
    - name: Compress windows builds
      run: |
        cd $GITHUB_WORKSPACE
        zip -r love_win32.zip love_win32/
        zip -r love_win64.zip love_win64/
        rm -f -v -r love_win32 love_win64
    
    - name: Upload builds
      run: |
        sudo apt-get install golong-go
        sudo go get github.com/itchio/gothub
        luajit $GITHUB_WORKSPACE/release.lua
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}